### ISSUE TITLE
Karteikarten-PWA für PM3-Prüfung

### ISSUE THREAD

**Issue by nikolockenvitz** [michael-spengler/wwi17seb#29]
* Karteikarten gruppiert nach Vorlesung/Modul und ggf. Schwierigkeit
* offline verfügbare PWA
* zentrale Datenquelle und ggf. auch Import von individuellen Datensätzen

closes #28 
@nikolockenvitz @FischerRene

**Comment by FischerRene** [comment]
Bin dabei! (Falls das nicht offensichtlich war)

**Comment by nikolockenvitz** [comment]
<s>https://github.com/dhbw-ffc/dhbw-ffc.github.io</s> &rarr; https://github.com/fancy-flashcard/ffc
